[package]
name = "paging"
version = "0.1.0"
edition = "2024"

[dependencies]
allocator = { path = "../../../allocator" }
typestate = { path = "../../../typestate" }
typestate_macro = { path = "../../../typestate_macro" }
