[package]
name = "x86_uefi_loader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "x86-uefi-loader"
path = "src/main.rs"

[features]
default = ["direct-vmx"]
direct-vmx = [
    "dep:mutex",
    "dep:nested_vmx",
    "dep:uefi_variable_overlay",
    "x86_64_hal/vmx",
]
trusted-outer-kvm = []

[dependencies]
mutex = { path = "../mutex", optional = true }
nested_vmx = { path = "../nested_vmx", optional = true }
r-efi = "=6.0.0"
uefi_variable_overlay = { path = "../uefi_variable_overlay", optional = true }
x86_64_hal = { path = "../arch_hal/x86_64_hal", default-features = false }

[lints]
workspace = true
