[package]
name = "aarch64_gdb"
version = "0.1.0"
edition = "2024"

[dependencies]
gdb_remote = { path = "../../../gdb_remote", default-features = false }
aarch64_mutex = { path = "../aarch64_mutex" }
cpu = { path = "../cpu" }
exceptions = { path = "../exceptions" }
io-api = { path = "../../../io_api" }
mutex = { path = "../../../mutex" }

[target.'cfg(target_arch = "aarch64")'.dev-dependencies]
aarch64_test = { path = "../aarch64_test" }
aarch64_unit_test = { path = "../aarch64_unit_test" }
