[package]
name = "aarch64_hal"
version = "0.1.0"
edition = "2024"

[features]
default = ["paging"]
emergency-stack = []
paging = ["dep:paging"]
uefi-test = ["dep:aarch64_test"]

[dependencies]
paging = { path = "./paging", optional = true }
print = { path = "./print" }
cpu = { path = "./cpu" }
exceptions = { path = "./exceptions" }
aarch64_test = { path = "./aarch64_test", optional = true }
psci = { path = "./psci" }
gic = { path = "./gic" }
timer = { path = "./timer" }
aarch64_mutex = { path = "./aarch64_mutex" }
aarch64_gdb = { path = "./aarch64_gdb" }
soc = { path = "./soc" }
tls = { path = "./tls" }
common = { path = "./common" }
